#!/usr/bin/env node
/**
 * Builds api/ub-api.js (UMD: <script> tag + require() + AMD) from api/ub-api.mjs
 * (the ESM source of truth). Zero dependencies: a small disciplined transform.
 *
 * The ESM source must only use these export forms, one per line at column 0:
 *   export function name(...
 *   export async function name(...
 *   export const NAME = ...
 * Anything else starting a line with `export` or `import` fails the build.
 *
 *   node api/build.mjs
 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const dir = dirname(fileURLToPath(import.meta.url));
const SRC = join(dir, 'ub-api.mjs');
const OUT = join(dir, 'ub-api.js');

const src = readFileSync(SRC, 'utf8');
const names = [];
let body = src
  .replace(/^export async function ([A-Za-z_$][\w$]*)/gm, (m, n) => { names.push(n); return `async function ${n}`; })
  .replace(/^export function ([A-Za-z_$][\w$]*)/gm, (m, n) => { names.push(n); return `function ${n}`; })
  .replace(/^export const ([A-Za-z_$][\w$]*)/gm, (m, n) => { names.push(n); return `const ${n}`; });

const strayExport = body.match(/^export\s/m);
const strayImport = body.match(/^import\s/m);
if (strayExport) { console.error(`build failed: unsupported export form: ${strayExport[0].trim()}...`); process.exit(1); }
if (strayImport) { console.error('build failed: ESM source must not contain import statements (zero dependencies)'); process.exit(1); }
if (!names.length) { console.error('build failed: no exports found'); process.exit(1); }

const umd = `/**
 * UB API v${/UB_API_VERSION = '([^']+)'/.exec(body)?.[1] || '0.0.0'} — UMD build (generated by build.mjs from ub-api.mjs; do not edit).
 * Zero-cost, zero-dependency client for The Urantia Book's exact text. See api/README.md.
 * Book text is fetched at runtime from public mirrors, never bundled.
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) { define([], factory); }
  else if (typeof exports === 'object' && typeof module !== 'undefined') { module.exports = factory(); }
  else { root.UBApi = factory(); }
}(typeof self !== 'undefined' ? self : this, function () {
'use strict';
${body}
return { ${names.join(', ')} };
}));
`;

writeFileSync(OUT, umd);
console.log(`wrote ${OUT} (${names.length} exports: ${names.join(', ')})`);

// ---------- self-check: the UMD build loads and exposes every export ----------
const require = createRequire(import.meta.url);
delete require.cache[require.resolve(OUT)];
const api = require(OUT);
const missing = names.filter(n => !(n in api));
if (missing.length) { console.error(`build self-check failed: missing exports: ${missing.join(', ')}`); process.exit(1); }
const client = api.createClient({ persist: false, fetchImpl: async () => { throw new Error('no network in build check'); } });
for (const m of ['getParagraph', 'getSection', 'search', 'verifyQuote', 'prefetchAll', 'listPapers', 'clearCache', 'stats']) {
  if (typeof client[m] !== 'function') { console.error(`build self-check failed: client.${m} is not a function`); process.exit(1); }
}
console.log('self-check ok: UMD loads, all exports present, client factory works');
